# -*- coding: utf-8 -*-
"""Resnet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybL037Ork9R2b2hB8sudmvUz4lkyX3N6
"""









